# -*- coding: utf-8 -*-
"""AI_Categorize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLahGM4aEC7wAxgiugKxZomb5Msi3WdT
"""

!pip install transformers fastapi uvicorn gradio

from transformers import pipeline
import gradio as gr

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

def categorize_complaint(complaint_text):
    categories = ["Health", "Transport", "Security", "Infrastructure", "Employment", "Others"]
    result = classifier(complaint_text, candidate_labels=categories)
    return f"Category: {result['labels'][0]} (Confidence: {result['scores'][0]:.2f})"

interface = gr.Interface(
    fn=categorize_complaint,
    inputs=gr.Textbox(lines=3, placeholder="Enter your complaint here..."),
    outputs="text",
    title="Government Complaint Classifier",
    description="Enter a complaint and the AI will categorize it into Health, Transport, Security, Infrastructure, or Others."
)

interface.launch()